# -*- coding: utf-8 -*-
"""IEA-15-240-RWT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LNqZAc9DdHqzq8qwuv7WJE-UETzUJX1b
"""

# Commented out IPython magic to ensure Python compatibility.
# %%javascript
# IPython.OutputArea.prototype._should_scroll = function(lines) {
#     return false;
# }

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
import os
import matplotlib.pyplot as plt
from xfoil import XFoil
from xfoil.model import Airfoil

from panel_allairfoil import panel
font = {'family' : 'Times New Roman',
        'size'   : 16}    
plt.rc('font', **font)

#'weight' : 'bold'

import matplotlib as mpl
mpl.rcParams['text.usetex'] = True
mpl.rcParams['text.latex.preamble'] = [r'\usepackage{amsmath}']

#%%
airfoil_names = ['SNL-FFA-W3-500', 
                 'FFA-W3-211',
                 'FFA-W3-241',
                 'FFA-W3-270blend',
                 'FFA-W3-301',
                 'FFA-W3-330blend',
                 'FFA-W3-360']

# circular airfoil
Airfoil_circular=pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil circular',       
                               skiprows=4,nrows=101,usecols="A:B")

# 
Airfoil_SNL_FFA_W3_500  = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil SNL-FFA-W3-500',
                                        skiprows=4,nrows=200,usecols="A:B")
Airfoil_SNL_FFA_W3_500_cfd = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil SNL-FFA-W3-500',
                                           skiprows=208,nrows=200,usecols="A:D")
Airfoil_SNL_FFA_W3_500_cfd['alpha [deg]'] = Airfoil_SNL_FFA_W3_500_cfd['alpha [rad]']*180/np.pi

#
Airfoil_FFA_W3_211 = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-211',
                                 skiprows=4,nrows=200,usecols="A:B")
Airfoil_FFA_W3_211_cfd = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-211',
                                 skiprows=208,nrows=200,usecols="A:D")
Airfoil_FFA_W3_211_cfd['alpha [deg]'] = Airfoil_FFA_W3_211_cfd['alpha [rad]']*180/np.pi


#
Airfoil_FFA_W3_241 = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-241',     
                                 skiprows=4,nrows=200,usecols="A:B")
Airfoil_FFA_W3_241_cfd = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-241',     
                                 skiprows=208,nrows=200,usecols="A:D")
Airfoil_FFA_W3_241_cfd['alpha [deg]'] = Airfoil_FFA_W3_241_cfd['alpha [rad]']*180/np.pi


#
Airfoil_FFA_W3_270blend = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-270blend',
                                        skiprows=4,nrows=257,usecols="A:B")
Airfoil_FFA_W3_270blend_cfd = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-270blend',
                                        skiprows=265,nrows=257,usecols="A:D")
Airfoil_FFA_W3_270blend_cfd['alpha [deg]'] = Airfoil_FFA_W3_270blend_cfd['alpha [rad]']*180/np.pi

#
Airfoil_FFA_W3_301 = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-301',    
                                   skiprows=4,nrows=200,usecols="A:B")
Airfoil_FFA_W3_301_cfd = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-301',    
                                   skiprows=208,nrows=200,usecols="A:D")
Airfoil_FFA_W3_301_cfd['alpha [deg]'] = Airfoil_FFA_W3_301_cfd['alpha [rad]']*180/np.pi

#
Airfoil_FFA_W3_330blend = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-330blend',
                                        skiprows=4,nrows=257,usecols="A:B")
Airfoil_FFA_W3_330blend_cfd = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-330blend',
                                        skiprows=265,nrows=257,usecols="A:D")
Airfoil_FFA_W3_330blend_cfd['alpha [deg]'] = Airfoil_FFA_W3_330blend_cfd['alpha [rad]']*180/np.pi

#
Airfoil_FFA_W3_360 = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-360',     
                                 skiprows=4,nrows=200,usecols="A:B")
Airfoil_FFA_W3_360_cfd = pd.read_excel('IEA-15-240-RWT_tabular.xlsx',sheet_name='Airfoil FFA-W3-360',     
                                 skiprows=208,nrows=201,usecols="A:D")
Airfoil_FFA_W3_360_cfd['alpha [deg]'] = Airfoil_FFA_W3_360_cfd['alpha [rad]']*180/np.pi

#Airfoil_circular.plot(x='x',y='y')
#Airfoil_SNL_FFA_W3_500.plot(x='x',y='y')
#Airfoil_FFA_W3_211.plot(x='x',y='y')
#Airfoil_FFA_W3_241.plot(x='x',y='y')
#Airfoil_FFA_W3_270blend.plot(x='x',y='y')
#Airfoil_FFA_W3_301.plot(x='x',y='y')
#Airfoil_FFA_W3_330blend.plot(x='x',y='y')
#Airfoil_FFA_W3_360.plot(x='x',y='y')

#%%
fig, ax = plt.subplots(1,1, figsize=(10,4))

l_all = [Airfoil_SNL_FFA_W3_500,Airfoil_FFA_W3_211,Airfoil_FFA_W3_241,
     Airfoil_FFA_W3_270blend,Airfoil_FFA_W3_301,Airfoil_FFA_W3_330blend,Airfoil_FFA_W3_360]

k = 0
for l in l_all:
    x = l['x']
    y = l['y']
    
    ax.plot(x,y, label=airfoil_names[k])
    k += 1

ax.set_ylabel('$y$')
ax.set_xlabel('$x$')
#ax.legend() 
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)   
plt.show()
fig.savefig('airfoil_shapes.png', dpi=100, bbox_inches = 'tight' )

#%%
aifoils = [Airfoil_SNL_FFA_W3_500, Airfoil_FFA_W3_211, Airfoil_FFA_W3_241, 
           Airfoil_FFA_W3_270blend, Airfoil_FFA_W3_301, 
           Airfoil_FFA_W3_330blend, Airfoil_FFA_W3_360]

aifoils_cfd = [Airfoil_SNL_FFA_W3_500_cfd, Airfoil_FFA_W3_211_cfd, Airfoil_FFA_W3_241_cfd,  
               Airfoil_FFA_W3_270blend_cfd, Airfoil_FFA_W3_301_cfd, Airfoil_FFA_W3_330blend_cfd, 
               Airfoil_FFA_W3_360_cfd]

re = [1.0e6, 1.8e6, 1.8e6, 1e7, 1e7, 1e7, 1e7]

#%%
aoa_l = -34
aoa_h = 34

fig,ax = plt.subplots(1,1, figsize=(9,8))

klist = [1]

for k in range(1):
    print(k)
    x = aifoils[k]['x'].values
    y = aifoils[k]['y'].values
    
    ang_low = -32
    ang_high = 32
    ang_spacing = 2
    
    xfc = XFoil()
    xfc.airfoil = Airfoil(x, y)
    xfc.Re = re[k]
    xfc.max_iter = 40
    ac, clc, cdc, cmc, cpminc = xfc.aseq(ang_low, ang_high, ang_spacing)
    
    df = aifoils_cfd[k].where(aifoils_cfd[k]['alpha [deg]'] >= aoa_l)
    df = df.where(aifoils_cfd[k] <= aoa_h)
    df = df.dropna() #.values
    
    cl_panel = []
    cdp_panel = []
    
    for aoa in df['alpha [deg]']:
        data_xy = aifoils[k].values
        CL, CDP, Cp, pp = panel(data_xy[:,:], alfader = aoa)
        cl_panel.append(CL)
        cdp_panel.append(CDP)
    
    cl_panel = np.array(cl_panel)
    cdp_panel = np.array(cdp_panel)
    
    ax.plot(df['alpha [deg]'], df['c_l'], lw = 2, label=airfoil_names[k])
    
    fig1,ax1 = plt.subplots(1,1, figsize=(8,8))
    
    ax1.plot(df['alpha [deg]'], df['c_l'], lw = 2, label='CFD ' + airfoil_names[k])
    ax1.plot(ac, clc, 'ro--', lw = 2, label='Xfoil ' + airfoil_names[k])
    ax1.plot(df['alpha [deg]'], cl_panel, 'g-.', lw = 2, label='Panel ' + airfoil_names[k])
    
    ax1.set_xlabel('AOA (degrees)')
    ax1.set_ylabel('$C_L$')
    
    ax.legend()
    ax1.legend()
    #ax.set_xlim([0,22])
    ax.set_ylim([-2.0, 2.5])
    ax1.set_ylim([-2.0, 2.5])
    
    fig1.savefig(airfoil_names[k] + '.png', dpi=100, bbox_inches = 'tight' )
    
    np.savez(airfoil_names[k] + '.npz', re = re[k], 
             aoa_cfd = df['alpha [deg]'], cl_cfd = df['c_l'], 
             aoa_xfoil = ac, cl_xfoil = clc, 
             aoa_panel = df['alpha [deg]'], cl_panel = cl_panel)
    
ax.set_xlabel('AOA (degrees)')
ax.set_ylabel('$C_L$')

plt.show()    
fig.savefig('all_airfoils.png', dpi=100, bbox_inches = 'tight' )
    
